import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import "@/public/styles/style.css";
import "@/public/styles/dashboard.css";
import Header from "./header";
import Sidebar from "./sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard | Promas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Header></Header>
        <main className="container flex gap-4">
          <Sidebar></Sidebar>
          <div>
            {children}
          </div>
        </main>

      </body>
    </html>
  );
}
